### PR TITLE
Todo List

### PR DESCRIPTION
**Pull request by mstanley-me**
# In this milestone I:

 - made the the structure of the To Do List project
 - Added some features
 
# work with:
 - Linters
 - HTML5/CSS3
 - JavaScript ES6
 - Webpack

### CODE REVIEW

**Review by Lameck1 — COMMENTED** [review]
Hi @mstanley-me, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have not git ignored the node_modules directory. This makes reviewing your project difficult to review because of the 5000+ files that live within the node_modules directory. Please add the node_modules directory to the `.gitignore` file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi Team👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request



**_You have submitted a project with your `node_modules` pushed to Github, kindly remove this folder by adding it to your `gitignore` file_**
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mstanley-me** [comment]
This is the first part
So I’ve to do what on it please!?

**Review by mmsesay — COMMENTED** [review]
Hi @mstanley-me, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has node_modules in your repo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mstanley-me** [comment]
Hello!
How are you doing?
Can you make a suggestion please!
Because i do my everything on it now

**Review by medaminedev66 — APPROVED** [review]
# Hi @mstanley-me , 

### Status: Approved ✔️

:+1: You have implemented all the suggestions. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- It would be better to remove `vscode` folder and `.DS_Store` file or ignore them by git (gitignore) to make your GitHub repository clean. They are not necessary to be in your GitHub repository.

**You may close this Pull Request and merge the changes**

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Amine Smahi_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
